var Instances = require('./calculator.js')
var ans1 = new Instances(2)
var ans2 = new Instances(3)
var ans3 = new Instances(4)
var ans4 = new Instances(9)
var ans5 = new Instances(12)
var ans6 = new Instances(14)
var ans7 = new Instances(21)
var ans8 = new Instances(1)
var ans9 = new Instances("2023")


console.log(ans1.Greeting())
console.log(ans2.Greeting())
console.log(ans3.Greeting())
console.log(ans4.Greeting())
console.log(ans5.Greeting())
console.log(ans6.Greeting())
console.log(ans7.Greeting())
console.log(ans8.Greeting())
console.log(ans9.Greeting())
